apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-precise-humpback
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "291005901394"
    project: camunda-researchanddevelopment
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: salaboy
    repository: new-jx3-cluster
  - key: staging
  - key: production
  ingress:
    domain: 34.67.22.199.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: salaboy
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-precise-humpback-227e838340c7
  - name: reports
    url: gs://reports-tf-jx-precise-humpback-227e838340c7
  - name: repository
    url: gs://repository-tf-jx-precise-humpback-227e838340c7
  vault: {}
  webhook: lighthouse
