filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
releases:
- chart: dev/camunda-cloud-go-client
  version: 0.0.1
  name: camunda-cloud-go-client
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
